In [1]:
# Test of the circuit from "Crossing a topological phase transition with a quantum computer" (https://arxiv.org/pdf/1910.05351.pdf)

In [1]:
from typing import Any

import sympy
import math
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import numpy as np
from cirq import GridQubit, ops
from qsgenerator.phase.analitical import construct_hamiltonian, get_theta_v, get_theta_w, get_theta_r
from qsgenerator.phase.circuits import build_ground_state_circuit, build_u1_gate, build_u_gate
from qsgenerator.states.simple_state_circuits import build_x_rotation_state


In [52]:
size = 3# size of quantum circuit excluding boundary qubits

In [113]:
g = -1 # G parameter from the paper 

In [114]:
H = construct_hamiltonian(size, g)
lam, V = np.linalg.eigh(H)

# ground state wavefunction
psi = V[:, 0] / np.linalg.norm(V[:, 0])

In [115]:
real, real_symbols = build_ground_state_circuit(size=size)

In [116]:
resolver = cirq.ParamResolver({'theta_v': get_theta_v(g), 'theta_w': get_theta_w(g), 'theta_r': get_theta_r(g)})

In [117]:
resolved = cirq.resolve_parameters(real, resolver)

In [118]:
final_state = cirq.final_state_vector(resolved)

In [119]:
final_state

array([ 0.1767766 +0.j,  0.1767766 +0.j,  0.1767766 +0.j, -0.17677659+0.j,
       -0.17677662+0.j, -0.17677662+0.j,  0.17677665+0.j, -0.17677662+0.j,
       -0.1767766 +0.j, -0.1767766 +0.j, -0.1767766 +0.j,  0.17677659+0.j,
       -0.17677662+0.j, -0.17677662+0.j,  0.17677665+0.j, -0.17677662+0.j,
       -0.1767766 +0.j, -0.1767766 +0.j, -0.1767766 +0.j,  0.17677659+0.j,
        0.17677662+0.j,  0.17677662+0.j, -0.17677665+0.j,  0.17677662+0.j,
       -0.1767766 +0.j, -0.1767766 +0.j, -0.1767766 +0.j,  0.17677659+0.j,
       -0.17677662+0.j, -0.17677662+0.j,  0.17677665+0.j, -0.17677662+0.j],
      dtype=complex64)

In [120]:
partials = cirq.partial_trace_of_state_vector_as_mixture(final_state, [1,2,3])
partials

((0.2499997466802597,
  array([ 0.38151   +0.j, -0.3231874 +0.j, -0.38151002+0.j, -0.32318747+0.j,
         -0.38151   +0.j,  0.3231874 +0.j, -0.38151002+0.j, -0.32318747+0.j],
        dtype=complex64)),
 (0.2499997466802597,
  array([ 0.39806467+0.j, -0.30256322+0.j, -0.3980647 +0.j, -0.30256325+0.j,
          0.39806467+0.j, -0.30256322+0.j,  0.3980647 +0.j,  0.30256325+0.j],
        dtype=complex64)),
 (0.2499997764825821,
  array([ 0.32318744-0.j,  0.38150996+0.j, -0.32318747+0.j,  0.38151008+0.j,
         -0.3231874 +0.j, -0.38150993+0.j, -0.32318744+0.j,  0.38151002+0.j],
        dtype=complex64)),
 (0.2499997764825821,
  array([-0.3025632 +0.j, -0.3980646 +0.j,  0.30256325+0.j, -0.3980647 +0.j,
         -0.30256322+0.j, -0.39806464+0.j, -0.30256328+0.j,  0.39806473+0.j],
        dtype=complex64)))

In [121]:
psi

array([ 0.35355339, -0.35355339, -0.35355339, -0.35355339, -0.35355339,
       -0.35355339, -0.35355339,  0.35355339])

In [122]:
for p in partials:
    print(p[0], cirq.fidelity(p[1], psi))

0.2499997466802597 0.29109976691641815
0.2499997466802597 0.1830890225454351
0.2499997764825821 0.2089002146716102
0.2499997764825821 0.3169109914231965


In [12]:
g = -0.5
theta_w = get_theta_w(g)
theta_v = get_theta_v(g)
theta_r = get_theta_r(g)

q1, q2 = cirq.GridQubit.rect(1, 2)
cirq.unitary(build_u1_gate(q1, q2, theta_r))

array([[ 0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
         0.57735027+0.j],
       [ 0.57735027+0.j, -0.40824829+0.j,  0.57735027+0.j,
        -0.40824829+0.j],
       [ 0.57735027+0.j,  0.40824829+0.j, -0.57735027+0.j,
        -0.40824829+0.j],
       [-0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
        -0.57735027+0.j]])

In [27]:
g = -1

In [28]:
size
x_rot, x_rot_symbols = build_x_rotation_state(size=size)

In [29]:
x_resolver = cirq.ParamResolver({'r0': get_theta_v(g), 'r1': get_theta_w(g), 'r2': get_theta_r(g)})

In [30]:
x_resolved = cirq.resolve_parameters(x_rot, x_resolver)

In [31]:
cirq.final_state_vector(x_resolved)

array([ 0.24999999+0.j        ,  0.        -0.24999999j,
        0.        -0.60355335j, -0.60355335+0.j        ,
        0.        -0.10355338j, -0.10355338+0.j        ,
       -0.24999999+0.j        ,  0.        +0.24999999j], dtype=complex64)