In [ ]:
# Test of the circuit from "Crossing a topological phase transition with a quantum computer" (https://arxiv.org/pdf/1910.05351.pdf)

In [77]:
from typing import Any

import sympy
import math
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import numpy as np
from cirq import GridQubit, ops
from qugans.phase_transition import construct_hamiltonian, build_ground_state_circuit, \
    get_theta_v, get_theta_w, get_theta_r, U3


In [57]:
size = 5 # size of quantum circuit excluding boundary qubits

In [81]:
g = -0.5 # G parameter from the paper 

In [82]:
H = construct_hamiltonian(size-2, g)
lam, V = np.linalg.eigh(H)

# ground state wavefunction
psi = V[:, 0] / np.linalg.norm(V[:, 0])

In [83]:
real, real_symbols = build_ground_state_circuit(size=size)

In [84]:
resolver = cirq.ParamResolver({'theta_v': get_theta_v(g), 'theta_w': get_theta_w(g), 'theta_r': get_theta_r(g)})

In [85]:
resolved = cirq.resolve_parameters(real, resolver)

In [72]:
final_state = cirq.final_state_vector(resolved)

In [73]:
cirq.partial_trace_of_state_vector_as_mixture(final_state, [1,2,3])

((0.49999991059303284,
  array([0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        dtype=complex64)),
 (0.49999991059303284,
  array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        dtype=complex64)))

In [74]:
psi

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
theta_w = get_theta_w(g)
theta_v = get_theta_v(g)
theta_r = get_theta_r(g)
g = -0.5
q1, q2 = cirq.GridQubit.rect(1, 2)
cirq.unitary(cirq.Circuit(
        cirq.H(q1),
        cirq.CNOT(q1, q2),
        U3(theta_r, 0, np.pi).on(q2)
    ))

array([[ 0.40824829+0.00000000e+00j,  0.57735027-7.07050159e-17j,
         0.40824829+0.00000000e+00j,  0.57735027-7.07050159e-17j],
       [ 0.57735027+0.00000000e+00j, -0.40824829+4.99959962e-17j,
         0.57735027+0.00000000e+00j, -0.40824829+4.99959962e-17j],
       [ 0.57735027-7.07050159e-17j,  0.40824829+0.00000000e+00j,
        -0.57735027+7.07050159e-17j, -0.40824829+0.00000000e+00j],
       [-0.40824829+4.99959962e-17j,  0.57735027+0.00000000e+00j,
         0.40824829-4.99959962e-17j, -0.57735027+0.00000000e+00j]])