In [ ]:
# Test of the circuit from "Crossing a topological phase transition with a quantum computer" (https://arxiv.org/pdf/1910.05351.pdf)

In [1]:
from typing import Any

import sympy
import math
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import numpy as np
from cirq import GridQubit, ops
from qsgenerator.phase.analitical import construct_hamiltonian, get_theta_v, get_theta_w, get_theta_r
from qsgenerator.phase.circuits import build_ground_state_circuit, build_u1_gate, build_u_gate


In [2]:
size = 5 # size of quantum circuit excluding boundary qubits

In [33]:
g = 0 # G parameter from the paper 

In [34]:
H = construct_hamiltonian(size-2, g)
lam, V = np.linalg.eigh(H)

# ground state wavefunction
psi = V[:, 0] / np.linalg.norm(V[:, 0])

In [35]:
real, real_symbols = build_ground_state_circuit(size=size)

In [36]:
resolver = cirq.ParamResolver({'theta_v': get_theta_v(g), 'theta_w': get_theta_w(g), 'theta_r': get_theta_r(g)})

In [37]:
resolved = cirq.resolve_parameters(real, resolver)

In [38]:
final_state = cirq.final_state_vector(resolved)

In [39]:
cirq.partial_trace_of_state_vector_as_mixture(final_state, [1,2,3])

((0.49999991059303284,
  array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        dtype=complex64)),
 (0.49999991059303284,
  array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
        dtype=complex64)))

In [18]:
psi

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
g = -0.5
theta_w = get_theta_w(g)
theta_v = get_theta_v(g)
theta_r = get_theta_r(g)

q1, q2 = cirq.GridQubit.rect(1, 2)
cirq.unitary(build_u1_gate(q1, q2, theta_r))

array([[ 0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
         0.57735027+0.j],
       [ 0.57735027+0.j, -0.40824829+0.j,  0.57735027+0.j,
        -0.40824829+0.j],
       [ 0.57735027+0.j,  0.40824829+0.j, -0.57735027+0.j,
        -0.40824829+0.j],
       [-0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
        -0.57735027+0.j]])