In [ ]:
# Test of the circuit from "Crossing a topological phase transition with a quantum computer" (https://arxiv.org/pdf/1910.05351.pdf)

In [1]:
from typing import Any

import sympy
import math
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import numpy as np
from cirq import GridQubit, ops
from qsgenerator.phase.analitical import construct_hamiltonian, get_theta_v, get_theta_w, get_theta_r
from qsgenerator.phase.circuits import build_ground_state_circuit, build_u1_gate, build_u_gate


In [2]:
size = 5 # size of quantum circuit excluding boundary qubits

In [3]:
g = -0.5 # G parameter from the paper 

In [4]:
H = construct_hamiltonian(size-2, g)
lam, V = np.linalg.eigh(H)

# ground state wavefunction
psi = V[:, 0] / np.linalg.norm(V[:, 0])

In [5]:
real, real_symbols = build_ground_state_circuit(size=size)

In [6]:
resolver = cirq.ParamResolver({'theta_v': get_theta_v(g), 'theta_w': get_theta_w(g), 'theta_r': get_theta_r(g)})

In [7]:
resolved = cirq.resolve_parameters(real, resolver)

In [8]:
final_state = cirq.final_state_vector(resolved)

In [9]:
cirq.partial_trace_of_state_vector_as_mixture(final_state, [1,2,3])

((1.297202167904743e-08,
  array([-0.14231484+0.j, -0.655968  +0.j, -0.28462976+0.j,  0.6559681 +0.j,
         -0.01234258+0.j,  0.17398722+0.j,  0.01234258+0.j,  0.08699358+0.j],
        dtype=complex64)),
 (0.22222235798835754,
  array([-4.1765369e-07+0.j, -6.9212675e-01+0.j,  2.1320021e-07+0.j,
         -6.9212663e-01+0.j,  1.4477780e-01+0.j,  1.8238600e-07+0.j,
          1.4477783e-01+0.j, -2.6540948e-07+0.j], dtype=complex64)),
 (0.22222240269184113,
  array([ 5.8691541e-07+0.j,  1.4477785e-01+0.j, -3.4129999e-07+0.j,
          1.4477779e-01+0.j,  6.9212675e-01+0.j,  1.1928316e-07+0.j,
          6.9212669e-01+0.j, -2.4118532e-07+0.j], dtype=complex64)),
 (0.2777779996395111,
  array([ 3.8347012e-01-0.j, -3.5041143e-07+0.j, -1.9173501e-01+0.j,
         -3.4048148e-07+0.j,  2.8269463e-08+0.j, -4.0402678e-01+0.j,
          4.7737654e-08+0.j,  8.0805367e-01+0.j], dtype=complex64)),
 (0.27777808904647827,
  array([-8.0805367e-01+0.j,  3.0298011e-07+0.j,  4.0402669e-01+0.j,
          3.

In [10]:
psi

array([-0.53452248,  0.26726124,  0.26726124,  0.26726124,  0.26726124,
        0.26726124,  0.26726124, -0.53452248])

In [38]:
g = -0.5
theta_w = get_theta_w(g)
theta_v = get_theta_v(g)
theta_r = get_theta_r(g)

q1, q2 = cirq.GridQubit.rect(1, 2)
cirq.unitary(build_u1_gate(q1, q2, theta_r))

array([[ 0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
         0.57735027+0.j],
       [ 0.57735027+0.j, -0.40824829+0.j,  0.57735027+0.j,
        -0.40824829+0.j],
       [ 0.57735027+0.j,  0.40824829+0.j, -0.57735027+0.j,
        -0.40824829+0.j],
       [-0.40824829+0.j,  0.57735027+0.j,  0.40824829+0.j,
        -0.57735027+0.j]])